Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,8 +43,8 @@ jobs:
           GITHUB_AUTHOR_PROFILE_ICON="https://avatars.githubusercontent.com/${GITHUB_ACTOR}"
           COMMIT_HASH=$(git log -1 --pretty=format:'%H')
           COMMIT_TIMESTAMP=$(git log -1 --pretty=format:'%cI')
+
           echo "title=${COMMIT_TITLE}" >> $GITHUB_ENV
-          
           echo "author_name=${GITHUB_AUTHOR_NAME}" >> $GITHUB_ENV
           echo "author_url=https://github.com/${GITHUB_ACTOR}" >> $GITHUB_ENV
           echo "author_profileicon=${GITHUB_AUTHOR_PROFILE_ICON}" >> $GITHUB_ENV
@@ -56,8 +56,8 @@ jobs:
         id: check_commit_message
         run: |
           if [[ "${{ env.title }}" == *"[ignore changelog]"* ]]; then
-            echo "::error::Commit message starts with '[ignore changelog]'. Skipping Discord notification."
-            exit 1
+            echo "::error::Commit message includes '[ignore changelog]'. Skipping Discord notification."
+            echo "skip_discord_notification=true" >> $GITHUB_ENV
           else
             echo "skip_discord_notification=false" >> $GITHUB_ENV
           fi
@@ -66,6 +66,11 @@ jobs:
         env:
           DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
         run: |
+          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
+            echo "::error::DISCORD_WEBHOOK_URL is not set."
+            exit 1
+          fi
+
           for i in {1..5}; do
             response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H 'Content-Type: application/json' -d '{
               "content": null,
@@ -87,7 +92,8 @@ jobs:
               ],
               "username": "${{ env.username }}",
               "attachments": []
-            }' $DISCORD_WEBHOOK_URL)
+            }' "$DISCORD_WEBHOOK_URL")
+            
             if [ $response -eq 204 ]; then
               echo "Discord notification sent successfully."
               break
